### ISSUE TITLE
Build Errors

### ISSUE THREAD

**Issue by krb09** [DNJha/IoTSim-Edge#2]
Hello,

I have been trying to run the examples on IoTSim-Edge. I am following the **User Manuel** as well as went through the closed issue **Compilation Errors #1**. 

I am receiving build errors, i.e. BUILD FAILURE. I have attached the full output log when I run Maven Install. 

[IoTSim_Error.txt](https://github.com/DNJha/IoTSim-Edge/files/4282867/IoTSim_Error.txt)

Please let me know if there are any resources that you can point out or any other information needed from my side.

**Comment by DNJha** [comment]
Hi,

Can you please try to run an example and see if you got any error. Please send me the error log.

There is some bug in our code that create build failure, we are still working on fixing that.

**Comment by krb09** [comment]
Hello,

Thank you for the prompt reply. 

I tried running the example 1 and it worked perfectly. No error messages. The simulation is complete and I receive an output.

So should I ignore the "Build Failure" error message? 

Thank you

**Comment by DNJha** [comment]
Good to hear that.

Please ignore the build failure for now. We'll have a fix soon.
