### ISSUE TITLE
CloudSim jar file location missing

### ISSUE THREAD

**Issue by sardarkhaleeq24** [DNJha/IoTSim-Edge#4]
Hi, dear in the readme file its mentioned that "One has to change the location of CloudSim jar file to compile succesfully." But where do we need to move this file? no next location is mentioned.

**Comment by DNJha** [comment]
Hi, CloudSim jar is already provided in the EdgeIoTSim\lib folder of the project. For adding this jar file to the working project, you need to go to Properties > Java Build path > Add External Jars...  and then go to the location of CloudSim package and add that. 

Please let me know if you have any other questions.

**Comment by sardarkhaleeq24** [comment]
> Hi, CloudSim jar is already provided in the EdgeIoTSim\lib folder of the project. For adding this jar file to the working project, you need to go to Properties > Java Build path > Add External Jars... and then go to the location of CloudSim package and add that.
> 
> Please let me know if you have any other questions.

Thanks a lot. Yes it worked. Now there are 87 (pasted below) warnings. Should i ignore them?


Build path specifies execution environment JavaSE-1.8. There are no JREs installed in the workspace that are strictly compatible with this environment. 
Class is a raw type. References to generic type Class<T> should be parameterized
Class is a raw type. References to generic type Class<T> should be parameterized
Class is a raw type. References to generic type Class<T> should be parameterized
Class is a raw type. References to generic type Class<T> should be parameterized
Class is a raw type. References to generic type Class<T> should be parameterized
Class is a raw type. References to generic type Class<T> should be parameterized
Class is a raw type. References to generic type Class<T> should be parameterized
Class is a raw type. References to generic type Class<T> should be parameterized
Class is a raw type. References to generic type Class<T> should be parameterized
Class is a raw type. References to generic type Class<T> should be parameterized
Class is a raw type. References to generic type Class<T> should be parameterized
Class is a raw type. References to generic type Class<T> should be parameterized
Class is a raw type. References to generic type Class<T> should be parameterized
Class is a raw type. References to generic type Class<T> should be parameterized
Class is a raw type. References to generic type Class<T> should be parameterized
Class is a raw type. References to generic type Class<T> should be parameterized
Class is a raw type. References to generic type Class<T> should be parameterized
Class is a raw type. References to generic type Class<T> should be parameterized
Class is a raw type. References to generic type Class<T> should be parameterized
Class is a raw type. References to generic type Class<T> should be parameterized
Class is a raw type. References to generic type Class<T> should be parameterized
Class is a raw type. References to generic type Class<T> should be parameterized
Class is a raw type. References to generic type Class<T> should be parameterized
Class is a raw type. References to generic type Class<T> should be parameterized
The compiler compliance specified is 1.8 but a JRE 13 is used
The import java.io.FileOutputStream is never used
The import java.io.IOException is never used
The import java.net.URL is never used
The import java.util.Enumeration is never used
The import java.util.logging.Logger is never used
The import java.util is never used
The import java.util is never used
The import java.util is never used
The import java.util is never used
The import javafx.collections.ObservableList is never used
The import javafx.scene.layout.HBox is never used
The import javax.swing.text.html.parser.Entity is never used
The import org.cloudbus.cloudsim.Host is never used
The import org.cloudbus.cloudsim.Log is never used
The import org.cloudbus.cloudsim.Log is never used
The import org.cloudbus.cloudsim.Log is never used
The import org.cloudbus.cloudsim.Log is never used
The import org.cloudbus.cloudsim.power.PowerVm is never used
The import org.edge.core.edge.EdgeDevice is never used
The import org.edge.core.iot.IoTDevice is never used
The import org.edge.entity.ConfiguationEntity.IotDeviceEntity is never used
The import org.edge.network.NetworkType is never used
The import org.edge.utils.NumberTextField is never used
The import org.edge.utils.PackageUtils is never used
The method actuating(SimEvent) from the type EdgeDataCenterBroker is never used locally
The method newInstance() from the type Class<capture#4-of ?> is deprecated
The method newInstance() from the type Class<capture#4-of ?> is deprecated
The method newInstance() from the type Class<capture#4-of ?> is deprecated
The method newInstance() from the type Class<capture#4-of ?> is deprecated
The method newInstance() from the type Class<capture#5-of ?> is deprecated
The method newInstance() from the type Class<capture#5-of ?> is deprecated
The method newInstance() from the type Class<capture#5-of ?> is deprecated
The method newInstance() from the type Class<capture#5-of ?> is deprecated
The value of the field ConnectionCreation.primaryStage is not used
The value of the field EdgeDataCenterCreation.primaryStage is not used
The value of the field EdgeDevice.type is not used
The value of the field EdgeDeviceCreation.primaryStage is not used
The value of the field IoTDevice.complexityOfDataPackage is not used
The value of the field IoTDevice.dataPackagesUnderTransmission is not used
The value of the field IoTDevice.isMoving is not used
The value of the field IoTDevice.pesNumber is not used
The value of the field LogUtil.path is not used
The value of the field Main.primaryStage is not used
The value of the field Simulator.loTDevices is not used
The value of the field VMCreation.primaryStage is not used
The value of the local variable cost is not used
The value of the local variable device is not used
The value of the local variable e is not used
The value of the local variable indent is not used
The value of the local variable indent is not used
The value of the local variable indent is not used
The value of the local variable indent is not used
Type safety: The expression of type Class[] needs unchecked conversion to conform to Class<? extends CommunicationProtocol>[]
Type safety: The expression of type Class[] needs unchecked conversion to conform to Class<? extends CommunicationProtocol>[]
Type safety: The expression of type Class[] needs unchecked conversion to conform to Class<? extends CommunicationProtocol>[]
Type safety: The expression of type Class[] needs unchecked conversion to conform to Class<? extends CommunicationProtocol>[]
Type safety: The expression of type Class[] needs unchecked conversion to conform to Class<? extends IoTDevice>[]
Type safety: The expression of type Class[] needs unchecked conversion to conform to Class<? extends IoTDevice>[]
Type safety: The expression of type Class[] needs unchecked conversion to conform to Class<? extends IoTDevice>[]
Type safety: The expression of type Class[] needs unchecked conversion to conform to Class<? extends IoTDevice>[]
Type safety: The method isAssignableFrom(Class) belongs to the raw type Class. References to generic type Class<T> should be parameterized

**Comment by DNJha** [comment]
Yes, you can ignore the warning. There is some bug which may lead to build failure but you can run the examples successfully.
