### ISSUE TITLE
Offloading decision code

### ISSUE THREAD

**Issue by maqsood-tahir** [DNJha/IoTSim-Edge#5]
Hi,

I want to implement a customized computation offloading scheme in IoTSim-Edge. Can you please guide that where (in which file/function) offloading decision is taken. Thanks!

**Comment by DNJha** [comment]
Dear Maqsood,

In the current version of the simulator, there is only data shrinking in terms of offloading which is set manually either in the FilterOperation.java of org.edge.core.feature.operation package or in the configuration file. You can add a new class in the same package to create a method for making the offloading decisions.

Let me know if you have any other questions.

**Comment by maqsood-tahir** [comment]
Dear DNJha,

Many thanks for the clarification and guidance. Will contact you if any further help is required.
